# This workflow will install Python dependencies, build the binaries for Windows and Ubuntu, and copy the "sounds" directory.

name: Manual Build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt pyinstaller

      - name: Build binary
        run: pyinstaller -F --noconsole -n breakout hbreakout.py

      - name: Move binary and create sounds folder
        run: |
          mkdir dist\windows-output\breakout
          move dist\breakout.exe dist\windows-output\breakout\  # Move binary to ensure it's in the right folder
          mkdir dist\windows-output\sounds
          xcopy /E /I sounds dist\windows-output\sounds

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: |
            dist/windows-output/breakout/*  # Ensure the binary is included
            dist/windows-output/sounds/*  # Include sounds

  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt pyinstaller

      - name: Build binary
        run: pyinstaller -F --noconsole -n breakout hbreakout.py

      - name: Move binary and create sounds folder
        run: |
          mkdir -p dist/ubuntu-output/breakout
          mv dist/breakout dist/ubuntu-output/breakout/  # Move binary to ensure it's in the right folder
          mkdir -p dist/ubuntu-output/sounds
          cp -r sounds dist/ubuntu-output/sounds

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-binary
          path: |
            dist/ubuntu-output/breakout/*  # Ensure the binary is included
            dist/ubuntu-output/sounds/*  # Include sounds
