name: Build All

on: 
  workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest, 'macos-latest']

    steps:
- uses: actions/checkout@v4
- uses: actions/setup-python@v5
  with:
    python-version: '3.10' 
- run: python hbreakout.py

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller -F --noconsole -n breakout.py hbreakout.py
    # Optionally verify that it works (provided that it does not need user interaction)
    - run: ./dist/your-code/your-code
    - uses: actions/upload-artifact@v2
      with:
        path: dist/*
