# This workflow will install Python dependencies, build the binaries for Windows and Ubuntu, and copy the "sounds" directory.

name: Manual Build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt pyinstaller

      - name: Build binary
        run: pyinstaller -F --noconsole -n breakout.exe hbreakout.py  # Use .exe as the name

      - name: Copy sounds directory
        run: |
          mkdir dist\win\breakout
          move dist\breakout.exe dist\win\breakout\
          mkdir dist\win\breakout\sounds
          xcopy /E /I sounds dist\breakout\sounds

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: |
            dist\win\breakout\breakout.exe
            dist\win\breakout\*
            dist\win\breakout\sounds\*

    build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt pyinstaller

      - name: Build binary
        run: pyinstaller -F --noconsole -n breakout hbreakout.py  # Ubuntu binary

      - name: Create output directory and copy sounds
        run: |
          mkdir -p dist/output/breakout
          mv dist/breakout dist/output/breakout  # Move binary to new location
          mkdir -p dist/output/sounds
          cp -r sounds/* dist/output/sounds/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-binary
          path: |
            dist/output/breakout  # Path to the binary
            dist/output/*
            dist/output/sounds/*  # Path to the sounds

