# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: os: ['windows-latest', 'ubuntu-latest]

    steps:
- uses: actions/checkout@v4
- uses: actions/setup-python@v5
  with:
    python-version: '3.10' 
- run: python hbreakout.py

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller -F --noconsole -n breakout.py hbreakout.py
    # Optionally verify that it works (provided that it does not need user interaction)
    - run: ./dist/your-code/your-code
    - uses: actions/upload-artifact@v2
      with:
        path: dist/*
